# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b03789e9c98c573b069d38eeb63b8b95c2e0adbc32a5f294a1a9d66dffe06b2eedc9e0159268c72256ece0b8cd019ca101947128122efb3c9dd438a0dfba645b

test:
  secret_key_base: 1bd9f9b45c4768685a001c6c70a25eabb424eadf7661ffb27591659261e90eb4d8edbe2fdfe405d35dc58d7ea79d848d53498d3c2bd4e20a806102f78b0acfcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
