# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b62edf09d5af55c2216d06f41dc560e8aa4744da6089cdb5a63d18316f4c7eb517bdc1e74413886ee3710302f4dc0e1dfc5efc1d4df393222fabd51f503347d0

test:
  secret_key_base: 6ebcc38aae8a6d845ea48e94f9ffa6bebd6bf0ad6de8f23f2d108362e7035f193b6b4ddc030af65e5a2cdaab5d00a200e160dc4416e84365dc3d473f80c81abd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
